import {
  Dispatch,
  ReactNode,
  SetStateAction,
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import * as FileSystem from "expo-file-system/legacy";
import { Person, PERSON_COLORS, ReceiptAnalysis } from "../types/billing";
import { useI18n } from "../i18n/I18nProvider";
import { dictionaries, MessageKey } from "../i18n/messages";
import { readEncryptedJson, writeEncryptedJson } from "../services/EncryptedFileStore";

type Translator = (key: MessageKey, params?: Record<string, string | number>) => string;

function makeDefaultPersons(t: Translator): Person[] {
  return [
    { id: "person-1", name: t("person.defaultName", { n: 1 }), color: PERSON_COLORS[0], voiceTranscript: "", selectedItems: [], subtotal: 0, taxTipShare: 0, grandTotal: 0 },
    { id: "person-2", name: t("person.defaultName", { n: 2 }), color: PERSON_COLORS[1], voiceTranscript: "", selectedItems: [], subtotal: 0, taxTipShare: 0, grandTotal: 0 },
  ];
}

function interpolateTemplate(template: string, params: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => {
    const value = params[key];
    return value === undefined ? `{${key}}` : String(value);
  });
}

function resolveAutoGeneratedPersonIndex(name: string, maxIndex: number): number | null {
  if (!name.trim()) return null;
  const templates = Object.values(dictionaries)
    .map((dictionary) => dictionary["person.defaultName"])
    .filter((value): value is string => typeof value === "string");

  for (let index = 1; index <= maxIndex; index += 1) {
    for (const template of templates) {
      if (interpolateTemplate(template, { n: index }) === name) {
        return index;
      }
    }
  }

  return null;
}

interface AppStateContextValue {
  receiptAnalysis: ReceiptAnalysis | null;
  setReceiptAnalysis: (next: ReceiptAnalysis | null) => void;
  historyEntries: ReceiptHistoryEntry[];
  addHistoryEntry: (analysis: ReceiptAnalysis) => void;
  receiptImageUri: string | null;
  setReceiptImageUri: (next: string | null) => void;
  persons: Person[];
  setPersons: Dispatch<SetStateAction<Person[]>>;
  updatePerson: (id: string, updates: Partial<Person>) => void;
  userName: string | null;
  setUserName: (next: string | null) => void;
  isUserProfileLoaded: boolean;
  hasSeenOnboarding: boolean;
  setHasSeenOnboarding: (next: boolean) => void;
  isOnboardingLoaded: boolean;
  themeMode: "light" | "dark" | "system";
  setThemeMode: (next: "light" | "dark" | "system") => void;
}

export interface ReceiptHistoryEntry {
  id: string;
  createdAt: number;
  analysis: ReceiptAnalysis;
}

const HISTORY_STORAGE_FILE = `${FileSystem.documentDirectory}wesplit-history-v1.json`;
const USER_PROFILE_STORAGE_FILE = `${FileSystem.documentDirectory}wesplit-user-profile-v1.json`;
const ONBOARDING_STORAGE_FILE = `${FileSystem.documentDirectory}wesplit-onboarding-v1.json`;
const THEME_STORAGE_FILE = `${FileSystem.documentDirectory}wesplit-theme-v1.json`;
const HISTORY_LIMIT = 30;

const AppStateContext = createContext<AppStateContextValue | undefined>(undefined);

function isValidReceiptItem(value: unknown): boolean {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Partial<ReceiptAnalysis["items"][number]>;
  return (
    typeof candidate.id === "string" &&
    typeof candidate.name === "string" &&
    typeof candidate.quantity === "number" &&
    Number.isFinite(candidate.quantity) &&
    candidate.quantity >= 0 &&
    typeof candidate.unitPrice === "number" &&
    Number.isFinite(candidate.unitPrice) &&
    candidate.unitPrice >= 0
  );
}

function isValidReceiptAnalysis(value: unknown): value is ReceiptAnalysis {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Partial<ReceiptAnalysis>;
  return (
    Array.isArray(candidate.items) &&
    candidate.items.every((item) => isValidReceiptItem(item)) &&
    typeof candidate.subtotal === "number" &&
    Number.isFinite(candidate.subtotal) &&
    typeof candidate.tax === "number" &&
    Number.isFinite(candidate.tax) &&
    typeof candidate.tip === "number" &&
    Number.isFinite(candidate.tip) &&
    typeof candidate.currency === "string" &&
    typeof candidate.restaurantName === "string"
  );
}

function sanitizeReceiptAnalysisForHistory(analysis: ReceiptAnalysis): ReceiptAnalysis {
  return {
    items: analysis.items.map((item) => ({ ...item })),
    subtotal: analysis.subtotal,
    tax: analysis.tax,
    tip: analysis.tip,
    serviceFee: analysis.serviceFee ?? 0,
    currency: analysis.currency,
    restaurantName: analysis.restaurantName,
  };
}

function normalizeHistoryEntry(value: unknown): ReceiptHistoryEntry | null {
  if (!value || typeof value !== "object") return null;
  const candidate = value as Partial<ReceiptHistoryEntry>;
  if (typeof candidate.id !== "string" || typeof candidate.createdAt !== "number") {
    return null;
  }
  if (!isValidReceiptAnalysis(candidate.analysis)) {
    return null;
  }
  return {
    id: candidate.id,
    createdAt: candidate.createdAt,
    analysis: sanitizeReceiptAnalysisForHistory(candidate.analysis),
  };
}

export function AppStateProvider({ children }: { children: ReactNode }) {
  const { t } = useI18n();
  const [receiptAnalysis, setReceiptAnalysis] = useState<ReceiptAnalysis | null>(null);
  const [historyEntries, setHistoryEntries] = useState<ReceiptHistoryEntry[]>([]);
  const [receiptImageUri, setReceiptImageUri] = useState<string | null>(null);
  const [persons, setPersons] = useState<Person[]>(() => makeDefaultPersons(t));
  const [userName, setUserNameState] = useState<string | null>(null);
  const [isUserProfileLoaded, setIsUserProfileLoaded] = useState(false);
  const [hasSeenOnboarding, setHasSeenOnboardingState] = useState(false);
  const [isOnboardingLoaded, setIsOnboardingLoaded] = useState(false);
  const [themeMode, setThemeModeState] = useState<"light" | "dark" | "system">("system");

  const updatePerson = useCallback((id: string, updates: Partial<Person>) => {
    setPersons((prev) => prev.map((p) => (p.id === id ? { ...p, ...updates } : p)));
  }, []);

  const addHistoryEntry = useCallback((analysis: ReceiptAnalysis) => {
    setHistoryEntries((prev) => [
      {
        id: `history-${Date.now()}-${Math.floor(Math.random() * 10000)}`,
        createdAt: Date.now(),
        analysis: sanitizeReceiptAnalysisForHistory(analysis),
      },
      ...prev,
    ].slice(0, HISTORY_LIMIT));
  }, []);

  const setUserName = useCallback((next: string | null) => {
    const normalized = next?.trim() ?? "";
    setUserNameState(normalized ? normalized : null);
  }, []);

  const setHasSeenOnboarding = useCallback((next: boolean) => {
    setHasSeenOnboardingState(Boolean(next));
  }, []);

  const setThemeMode = useCallback((next: "light" | "dark" | "system") => {
    setThemeModeState(next === "dark" ? "dark" : next === "system" ? "system" : "light");
  }, []);

  useEffect(() => {
    let isMounted = true;
    const loadHistory = async () => {
      try {
        const parsed = await readEncryptedJson<unknown>(HISTORY_STORAGE_FILE);
        if (!parsed || !isMounted) {
          return;
        }
        if (Array.isArray(parsed)) {
          const normalized = parsed
            .map((entry) => normalizeHistoryEntry(entry))
            .filter((entry): entry is ReceiptHistoryEntry => entry !== null)
            .sort((a, b) => b.createdAt - a.createdAt)
            .slice(0, HISTORY_LIMIT);
          setHistoryEntries(normalized);
        }
      } catch {
        // Ignore malformed local cache and continue with empty history.
      }
    };
    loadHistory();
    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    let isMounted = true;
    const loadOnboardingState = async () => {
      try {
        const parsed = await readEncryptedJson<unknown>(ONBOARDING_STORAGE_FILE);
        if (!parsed || !isMounted) {
          return;
        }
        if (parsed && typeof parsed === "object") {
          const seen = (parsed as { seen?: unknown }).seen;
          if (typeof seen === "boolean") {
            setHasSeenOnboardingState(seen);
          }
        }
      } catch {
        // Ignore malformed cache and continue with onboarding visible.
      } finally {
        if (isMounted) {
          setIsOnboardingLoaded(true);
        }
      }
    };
    loadOnboardingState();
    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    let isMounted = true;
    const loadTheme = async () => {
      try {
        const parsed = await readEncryptedJson<unknown>(THEME_STORAGE_FILE);
        if (!parsed || !isMounted) {
          return;
        }
        if (typeof parsed !== "object") {
          return;
        }
        const mode = (parsed as { mode?: unknown }).mode;
        if (mode === "light" || mode === "dark" || mode === "system") {
          setThemeModeState(mode);
        }
      } catch {
        // Ignore malformed cache and keep default mode.
      }
    };
    loadTheme();
    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    let isMounted = true;
    const loadUserProfile = async () => {
      try {
        const parsed = await readEncryptedJson<unknown>(USER_PROFILE_STORAGE_FILE);
        if (!parsed || !isMounted) {
          return;
        }
        if (parsed && typeof parsed === "object") {
          const name = (parsed as { name?: unknown }).name;
          if (typeof name === "string" && name.trim()) {
            setUserNameState(name.trim());
          }
        }
      } catch {
        // Ignore malformed profile cache and continue with no saved name.
      } finally {
        if (isMounted) {
          setIsUserProfileLoaded(true);
        }
      }
    };
    loadUserProfile();
    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    const serializedHistory = historyEntries.map((entry) => ({
      ...entry,
      analysis: sanitizeReceiptAnalysisForHistory(entry.analysis),
    }));
    writeEncryptedJson(HISTORY_STORAGE_FILE, serializedHistory).catch(() => {
      // Best-effort persistence only.
    });
  }, [historyEntries]);

  useEffect(() => {
    if (!isUserProfileLoaded) {
      return;
    }
    if (!userName) {
      FileSystem.deleteAsync(USER_PROFILE_STORAGE_FILE, { idempotent: true }).catch(() => {
        // Best-effort persistence only.
      });
      return;
    }
    writeEncryptedJson(USER_PROFILE_STORAGE_FILE, { name: userName }).catch(() => {
      // Best-effort persistence only.
    });
  }, [isUserProfileLoaded, userName]);

  useEffect(() => {
    if (!isOnboardingLoaded) {
      return;
    }
    if (!hasSeenOnboarding) {
      FileSystem.deleteAsync(ONBOARDING_STORAGE_FILE, { idempotent: true }).catch(() => {
        // Best-effort persistence only.
      });
      return;
    }
    writeEncryptedJson(ONBOARDING_STORAGE_FILE, { seen: true }).catch(() => {
      // Best-effort persistence only.
    });
  }, [hasSeenOnboarding, isOnboardingLoaded]);

  useEffect(() => {
    writeEncryptedJson(THEME_STORAGE_FILE, { mode: themeMode }).catch(() => {
      // Best-effort persistence only.
    });
  }, [themeMode]);

  useEffect(() => {
    if (!userName) {
      return;
    }
    setPersons((prev) => {
      if (prev.length === 0) return prev;
      const first = prev[0];
      if (first.name === userName) {
        return prev;
      }
      const next = [...prev];
      next[0] = { ...first, name: userName };
      return next;
    });
  }, [userName]);

  useEffect(() => {
    setPersons((prev) => {
      if (prev.length === 0) return prev;
      let changed = false;
      const upperBound = Math.max(prev.length + 10, 30);
      const next = prev.map((person) => {
        if (userName && person.id === "person-1") {
          return person;
        }
        const autoIndex = resolveAutoGeneratedPersonIndex(person.name, upperBound);
        if (!autoIndex) {
          return person;
        }
        const localizedName = t("person.defaultName", { n: autoIndex });
        if (localizedName === person.name) {
          return person;
        }
        changed = true;
        return { ...person, name: localizedName };
      });
      return changed ? next : prev;
    });
  }, [t, userName]);

  const value = useMemo(
    () => ({
      receiptAnalysis,
      setReceiptAnalysis,
      historyEntries,
      addHistoryEntry,
      receiptImageUri,
      setReceiptImageUri,
      persons,
      setPersons,
      updatePerson,
      userName,
      setUserName,
      isUserProfileLoaded,
      hasSeenOnboarding,
      setHasSeenOnboarding,
      isOnboardingLoaded,
      themeMode,
      setThemeMode,
    }),
    [
      addHistoryEntry,
      hasSeenOnboarding,
      historyEntries,
      isOnboardingLoaded,
      isUserProfileLoaded,
      persons,
      receiptAnalysis,
      receiptImageUri,
      setHasSeenOnboarding,
      setThemeMode,
      setUserName,
      themeMode,
      updatePerson,
      userName,
    ],
  );

  return <AppStateContext.Provider value={value}>{children}</AppStateContext.Provider>;
}

export function useAppState() {
  const value = useContext(AppStateContext);
  if (!value) {
    throw new Error("useAppState must be used within AppStateProvider");
  }

  return value;
}
